### PR TITLE
Fixes #35, updates license to Apache 2.0

### LINKED ISSUE #35: re-license under MPLv2
I was wondering if you'd be open to re-licensing this project under a slightly more permissive license, like MPLv2? I'd like to contribute to a project that is under MIT using this, but I don't think its possible while this is LGPL.

### PR DESCRIPTION
**Pull request by banagale**

### CODE REVIEW

**Comment by NodeGuy** [comment]
Thank you, please also delete `LICENSE.LESSER` and update `package.json`.

**Comment by banagale** [comment]
You're welcome. Thanks for that feedback. I tried a 'quick pr' using the web-based editor. Always a mistake. :)

**Comment by NodeGuy** [comment]
Please do it, my attention is slammed beyond belief right now.

**Comment by NodeGuy** [comment]
I've changed the license to MPLv2.

**Pull request closed without merging**
